# Site settings
name: bbugnsang's boaring blog
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  css_class: 'highlight'

# Disqus Comment
comments: true

# Google Analytics
google_analytics:
  ua: UA-100042262-1
