# Site settings
name: bbugnsang's devlog
baseurl: ""
url: https://bbungsang.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  css_class: 'highlight'

# Disqus Comment
comments: true

# Google Analytics
google_analytics:
  id: UA-100042262-1

plugins:
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 7
  sort_reverse: true
